services:
  go_caddy_url_updater:
    image: ghcr.io/intro-skipper/go_caddy_url_updater:latest
    container_name: go_caddy_url_updater
    restart: unless-stopped
    environment:
      - GITHUB_SECRETKEY=${GITHUB_SECRETKEY}
      - CADDYFILE_PATH=/etc/caddy/Caddyfile
      - CADDY_CONTAINER=caddy
      - DOCKER_SOCK=/var/run/docker.sock
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - LOCATION=${LOCATION}
    volumes:
      - /home/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /var/run/docker.sock:/var/run/docker.sock
